// This file was autogenerated by the QCOS test suite on 05/22/2024 01:45:12

#include "test_utils.h"
#include "gtest/gtest.h"
#include "markowitz_data.h"

TEST(portfolio_test, markowitz)
{
    // Allocate and set sparse matrix data.
    QCOSCscMatrix* P = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));
    QCOSCscMatrix* A = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));
    QCOSCscMatrix* G = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));

    qcos_set_csc(P, markowitz_n, markowitz_n, markowitz_P_nnz, markowitz_P_x, markowitz_P_p, markowitz_P_i);
    qcos_set_csc(A, markowitz_p, markowitz_n, markowitz_A_nnz, markowitz_A_x, markowitz_A_p, markowitz_A_i);
    qcos_set_csc(G, markowitz_m, markowitz_n, markowitz_G_nnz, markowitz_G_x, markowitz_G_p, markowitz_G_i);

    QCOSSettings* settings = (QCOSSettings*)malloc(sizeof(QCOSSettings));
    set_default_settings(settings);
    settings->verbose = 1;
    QCOSSolver* solver = (QCOSSolver*)malloc(sizeof(QCOSSolver));

    QCOSInt exit = qcos_setup(solver, markowitz_n, markowitz_m, markowitz_p, P, markowitz_c, A, markowitz_b, G, markowitz_h, markowitz_l, markowitz_ncones, markowitz_q, settings);
    ASSERT_EQ(exit, QCOS_NO_ERROR);

    exit = qcos_solve(solver);
    ASSERT_EQ(exit, QCOS_SOLVED);

    ASSERT_NEAR(solver->sol->obj, markowitz_objopt, 1e-4);

    // Cleanup memory allocations. 
    qcos_cleanup(solver);
    free(P);
    free(A);
    free(G);
}
