// This file was autogenerated by the QCOS test suite on 05/25/2024 23:30:38

#include "test_utils.h"
#include "gtest/gtest.h"
#include "markowitz_cvxpy_data.h"

TEST(portfolio_test, markowitz_cvxpy)
{
    // Allocate and set sparse matrix data.
    QCOSCscMatrix* P;
    QCOSCscMatrix* A;
    QCOSCscMatrix* G;
    if(markowitz_cvxpy_P_nnz > 0) {
        P = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));
        qcos_set_csc(P, markowitz_cvxpy_n, markowitz_cvxpy_n, markowitz_cvxpy_P_nnz, markowitz_cvxpy_P_x, markowitz_cvxpy_P_p, markowitz_cvxpy_P_i);
    }
    else {
        P = nullptr;
    }
    if(markowitz_cvxpy_A_nnz > 0) {
        A = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));
        qcos_set_csc(A, markowitz_cvxpy_p, markowitz_cvxpy_n, markowitz_cvxpy_A_nnz, markowitz_cvxpy_A_x, markowitz_cvxpy_A_p, markowitz_cvxpy_A_i);
    }
    else {
        A = nullptr;
    }
    if(markowitz_cvxpy_G_nnz > 0) {
        G = (QCOSCscMatrix*)malloc(sizeof(QCOSCscMatrix));
        qcos_set_csc(G, markowitz_cvxpy_m, markowitz_cvxpy_n, markowitz_cvxpy_G_nnz, markowitz_cvxpy_G_x, markowitz_cvxpy_G_p, markowitz_cvxpy_G_i);
    }
    else {
        G = nullptr;
    }
    QCOSSettings* settings = (QCOSSettings*)malloc(sizeof(QCOSSettings));
    set_default_settings(settings);
    settings->verbose = 1;
    QCOSSolver* solver = (QCOSSolver*)malloc(sizeof(QCOSSolver));

    QCOSInt exit = qcos_setup(solver, markowitz_cvxpy_n, markowitz_cvxpy_m, markowitz_cvxpy_p, P, markowitz_cvxpy_c, A, markowitz_cvxpy_b, G, markowitz_cvxpy_h, markowitz_cvxpy_l, markowitz_cvxpy_nsoc, markowitz_cvxpy_q, settings);
    ASSERT_EQ(exit, QCOS_NO_ERROR);

    exit = qcos_solve(solver);
    ASSERT_EQ(exit, QCOS_SOLVED);

    // Expect relative error of objective to be less that 0.01%
    expect_rel_error(solver->sol->obj, markowitz_cvxpy_objopt, 1e-4);

    // Cleanup memory allocations. 
    qcos_cleanup(solver);
    free(P);
    free(A);
    free(G);
}
